[programs.localnet]
crunchy_vs_smooth = "J3HAbtgjPEMs3QhBARjk8FW6uY53qGkcSBexD9AXju6E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
